### ISSUE TITLE
manifest to bedpe script

### ISSUE THREAD

**Issue by rjsicko** [tommyau/bamclipper#1]
Thanks for this program! This is exactly what I am looking for to replicate MSR analysis using bcbio-nextgen. Do you have a script to convert a TruSight/TruSeq manifest file into primer bedpe file? I'm trying to replicate the bedpe in the example folder by manual manipulation and I'm getting slightly different internal end1 & start2's.

**Comment by tommyau** [comment]
Please refer to the Perl script [./scripts/manifest2bedpe.pl](https://github.com/tommyau/bamclipper/blob/master/scripts/manifest2bedpe.pl)  in the latest commit 80eee02a9fe2f59e8669b77ae8502051724ea667.
For example, 
`./scripts/manifest2bedpe.pl < TruSight-Myeloid-Manifest.txt > trusight_myeloid.bedpe`

**Comment by rjsicko** [comment]
thank you very much!

**Comment by garrulus-glandarius** [comment]
Thank you for the helpful script!
