### ISSUE TITLE
Primer Extension Methods

### ISSUE THREAD

**Issue by crutching** [tommyau/bamclipper#5]
Hi there,

I'm curious about paired-end designs utilizing a single primer.  Is this something that BamClipper can handle?

Thanks!

**Comment by tommyau** [comment]
We recently developed a variant of BAMClipper to handle single primer extension dataset but I am not sure whether it fits your dataset. Is your dataset  based on a commercially available gene panel like Qiagen Qiaseq? or ArcherDx?

**Comment by crutching** [comment]
Great, I'd love to try it out!  Otherwise, I will be writing my own. Yes, this is based on the QIAseq method, with UMIs.  I'm feeling good about adapter and UMI handling, now just trying to deal with the error rate in primer regions leading to incorrect allele frequency estimation.

**Comment by marcelcaraciolo** [comment]
We would also like to test it. Is it possible ?

**Comment by tommyau** [comment]
Please contact chau@hksh.com for further discussion. Thank you.
