### ISSUE TITLE
ERROR: BEDPE file (-p) is not defined

### ISSUE THREAD

**Issue by garrulus-glandarius** [tommyau/bamclipper#6]
What does "ERROR: BEDPE file (-p) is not defined" mean? I've used:
``` /usr/local/bin/bamclipper.sh -b `ls *bam` -p `ls *bedpe` -n 4 ```

**Comment by tommyau** [comment]
You may want to check the output of `ls *bedpe` to see if there is one and only one bedpe file available, so that your command would work.

**Comment by garrulus-glandarius** [comment]
Oh, I didn't mention that I've already checked this. There is only one BEDPE file, and it is detectable by ```ls *bedpe```.

**Comment by tommyau** [comment]
I tried this command locally and it works as usual.
```bash
./bamclipper.sh -b `ls *bam` -p `ls *bedpe` -n 4
```
Could you post here the output of `ls *bam` and `ls *bedpe`? One of the possibilities is the BEDPE file name contains special character, e.g. space. You may want to define the exact file names in the command line, or try something like (note the double quote):
```bash
./bamclipper.sh -b "`ls *bam`" -p "`ls *bedpe`" -n 4
```

**Comment by garrulus-glandarius** [comment]
Dear Tommy,

thank you for your time. 

The only way I've found to run bamclipper is like this:
```/usr/local/bin/bamclipper.sh -b ./LK_S2.bam -p ./TruSeq.bedpe -n 4```

Here are the outputs of ```ls```:

```> ls *bam```                                                                                                
```LK_S2.bam  LV_S3.bam  MA_S6.bam  MD_S1.bam  SL_S4.bam  VN_S5.bam```

```> ls *bedpe   ```                                                                                          
```TruSeq.bedpe```

The output of the command offered by you:

```>/usr/local/bin/bamclipper.sh -b "`ls *bam`" -p "`ls *bedpe`" -n 4```                                  
```ERROR: BAM file is not found (LK_S2.bam LV_S3.bam MA_S6.bam MD_S1.bam SL_S4.bam VN_S5.bam)```

These commands also didn't work (I wonder why...):

> /usr/local/bin/bamclipper.sh -b `./*bam` -p `./*bedpe` -n 4                                           
zsh: exec format error: ./LK_S2.bam
./TruSeq.bedpe: 1: ./TruSeq.bedpe: Syntax error: "(" unexpected ERROR: BAM file is not found (-p)

> /usr/local/bin/bamclipper.sh -b ./*bam -p ./TruSeq.bedpe -n 4                                         
ERROR: BEDPE file (-p) is not defined

> /usr/local/bin/bamclipper.sh -b `./*bam` -p ./TruSeq.bedpe -n 4                                   
zsh: exec format error: ./LK_S2.bam
ERROR: BAM file is not found (-p)

> /usr/local/bin/bamclipper.sh -b `ls ./*bam` -p ./TruSeq.bedpe -n 4                                    
ERROR: BEDPE file (-p) is not defined

> /usr/local/bin/bamclipper.sh -b `ls *bam` -p ./TruSeq.bedpe -n 4                 
ERROR: BEDPE file (-p) is not defined

**Comment by tommyau** [comment]
Yes, just like in README, you need to define one and only one file for BAM file (`-b`). The same applies to BEDPE file (`-p`). In your cases, you actually have multiple bam files and that's why using `ls *bam` will lead to error.
If you intention is to pass all bam files to bamclipper, then GNU parallel may help you:
```bash
ls *.bam | parallel './bamclipper.sh -b {} -p ./TruSeq.bedpe -n 4'
# do the job one by one, depending on how many files and how many CPU cores you have:
ls *.bam | parallel -j 1 './bamclipper.sh -b {} -p ./TruSeq.bedpe -n 4'
```

**Comment by garrulus-glandarius** [comment]
Oh, I see. Sorry for disturbing you. Thanks for your invaluable help.
